---
title: "Pairwise Comparisons (GSE137001)"
author: "James Dao"
output:
  html_notebook:
    toc: true
    toc_float: true
    code_folding: hide
    theme: cerulean
---

```{r include=FALSE}
library(enrichR)
library(tidyverse)
```

```{r include=FALSE}
# Load relevant data
source(file.path(here::here(), "analysis", "avg-expr-GSE137001", "get_lfc_dfs.R"))
```

# Pathway Heatmap

```{r}
# Get enrichr results and save to file
padj_cutoff <- 0.01
lfc_cutoff <- 0.5
dbs <- c("GO_Biological_Process_2021")

if (!file.exists("enriched_res.Rdata")) {
  enriched_res <- lapply(lfc_dfs, function(df) {
    genes <- df %>%
      filter(padj <= padj_cutoff & abs(log2FoldChange) >= lfc_cutoff) %>%
      pull(SYMBOL)
    
    return(enrichr(genes, dbs))
  })
  save(enriched_res, file = "enriched_res.Rdata")
} else {
  load("enriched_res.Rdata")
}
```


```{r}
# Extract combined scores from each enrichr result
pathways <- c("GO:0009267", "GO:0034198", "GO:0036003", "GO:0036500", "GO:1990928", "GO:0034599", "GO:0034976", "GO:0016236", "GO:0010506")

combined_scores <- lapply(enriched_res, function(res) {
  c_score <- res[["GO_Biological_Process_2021"]] %>%
    filter(str_detect(Term, paste(pathways, collapse="|"))) %>%
    arrange(Term) %>% 
    pull(Combined.Score)
  
  return(c_score)
})

combined_scores <- as.data.frame(combined_scores)

row.names(combined_scores) <- enriched_res[[1]][["GO_Biological_Process_2021"]] %>%
  filter(str_detect(Term, paste(pathways, collapse="|"))) %>%
  arrange(Term) %>%
  pull(Term) %>% 
  gsub(".+\\((.+)\\)", "\\1", .)
```

```{r}
enriched_res[[1]][["GO_Biological_Process_2021"]] %>%
  filter(str_detect(Term, paste(pathways, collapse="|"))) %>%
  arrange(Term) %>%
  pull(Term)
```

```{r}
pheatmap::pheatmap(
  combined_scores,
  cluster_cols = FALSE
)
```



# DEG Datatables and Volcano Plots {.tabset}

## `r substring(names(lfc_dfs)[[1]], 7)`

```{r}
# Datatable example
res <- lfc_dfs[[1]]
padj_cutoff <- 0.01
lfc_cutoff <- 0.5

res %>%
  select(SYMBOL, log2FoldChange, padj) %>%
  filter(padj <= padj_cutoff & abs(log2FoldChange) >= lfc_cutoff) %>%
  arrange(padj) %>% 
  DT::datatable() %>%
  DT::formatSignif(columns = 2:3, digits = 3)
```


```{r fig.height=7}
# Volcano plot example
EnhancedVolcano::EnhancedVolcano(
  res,
  lab = res$SYMBOL,
  x = "log2FoldChange",
  y = "padj",
  pCutoff = padj_cutoff,
  FCcutoff = lfc_cutoff,
  subtitle = sprintf(
    "Adjusted p-value cutoff = %0.2f
|Log2FoldChange| cutoff = %0.1f",
    padj_cutoff, lfc_cutoff
  )
)
```

## `r substring(names(lfc_dfs)[[2]], 7)`

```{r}
# Datatable example
res <- lfc_dfs[[2]]
padj_cutoff <- 0.01
lfc_cutoff <- 0.5

res %>%
  select(SYMBOL, log2FoldChange, padj) %>%
  filter(padj <= padj_cutoff & abs(log2FoldChange) >= lfc_cutoff) %>%
  arrange(padj) %>% 
  DT::datatable() %>%
  DT::formatSignif(columns = 2:3, digits = 3)
```


```{r fig.height=7}
# Volcano plot example
EnhancedVolcano::EnhancedVolcano(
  res,
  lab = res$SYMBOL,
  x = "log2FoldChange",
  y = "padj",
  pCutoff = padj_cutoff,
  FCcutoff = lfc_cutoff,
  subtitle = sprintf(
    "Adjusted p-value cutoff = %0.2f
|Log2FoldChange| cutoff = %0.1f",
    padj_cutoff, lfc_cutoff
  )
)
```

## `r substring(names(lfc_dfs)[[3]], 7)`

```{r}
# Datatable example
res <- lfc_dfs[[3]]
padj_cutoff <- 0.01
lfc_cutoff <- 0.5

res %>%
  select(SYMBOL, log2FoldChange, padj) %>%
  filter(padj <= padj_cutoff & abs(log2FoldChange) >= lfc_cutoff) %>%
  arrange(padj) %>% 
  DT::datatable() %>%
  DT::formatSignif(columns = 2:3, digits = 3)
```


```{r fig.height=7}
# Volcano plot example
EnhancedVolcano::EnhancedVolcano(
  res,
  lab = res$SYMBOL,
  x = "log2FoldChange",
  y = "padj",
  pCutoff = padj_cutoff,
  FCcutoff = lfc_cutoff,
  subtitle = sprintf(
    "Adjusted p-value cutoff = %0.2f
|Log2FoldChange| cutoff = %0.1f",
    padj_cutoff, lfc_cutoff
  )
)
```

## `r substring(names(lfc_dfs)[[4]], 7)`

```{r}
# Datatable example
res <- lfc_dfs[[4]]
padj_cutoff <- 0.01
lfc_cutoff <- 0.5

res %>%
  select(SYMBOL, log2FoldChange, padj) %>%
  filter(padj <= padj_cutoff & abs(log2FoldChange) >= lfc_cutoff) %>%
  arrange(padj) %>% 
  DT::datatable() %>%
  DT::formatSignif(columns = 2:3, digits = 3)
```


```{r fig.height=7}
# Volcano plot example
EnhancedVolcano::EnhancedVolcano(
  res,
  lab = res$SYMBOL,
  x = "log2FoldChange",
  y = "padj",
  pCutoff = padj_cutoff,
  FCcutoff = lfc_cutoff,
  subtitle = sprintf(
    "Adjusted p-value cutoff = %0.2f
|Log2FoldChange| cutoff = %0.1f",
    padj_cutoff, lfc_cutoff
  )
)
```

## `r substring(names(lfc_dfs)[[5]], 7)`

```{r}
# Datatable example
res <- lfc_dfs[[5]]
padj_cutoff <- 0.01
lfc_cutoff <- 0.5

res %>%
  select(SYMBOL, log2FoldChange, padj) %>%
  filter(padj <= padj_cutoff & abs(log2FoldChange) >= lfc_cutoff) %>%
  arrange(padj) %>% 
  DT::datatable() %>%
  DT::formatSignif(columns = 2:3, digits = 3)
```


```{r fig.height=7}
# Volcano plot example
EnhancedVolcano::EnhancedVolcano(
  res,
  lab = res$SYMBOL,
  x = "log2FoldChange",
  y = "padj",
  pCutoff = padj_cutoff,
  FCcutoff = lfc_cutoff,
  subtitle = sprintf(
    "Adjusted p-value cutoff = %0.2f
|Log2FoldChange| cutoff = %0.1f",
    padj_cutoff, lfc_cutoff
  )
)
```

## `r substring(names(lfc_dfs)[[6]], 7)`

```{r}
# Datatable example
res <- lfc_dfs[[6]]
padj_cutoff <- 0.01
lfc_cutoff <- 0.5

res %>%
  select(SYMBOL, log2FoldChange, padj) %>%
  filter(padj <= padj_cutoff & abs(log2FoldChange) >= lfc_cutoff) %>%
  arrange(padj) %>% 
  DT::datatable() %>%
  DT::formatSignif(columns = 2:3, digits = 3)
```


```{r fig.height=7}
# Volcano plot example
EnhancedVolcano::EnhancedVolcano(
  res,
  lab = res$SYMBOL,
  x = "log2FoldChange",
  y = "padj",
  pCutoff = padj_cutoff,
  FCcutoff = lfc_cutoff,
  subtitle = sprintf(
    "Adjusted p-value cutoff = %0.2f
|Log2FoldChange| cutoff = %0.1f",
    padj_cutoff, lfc_cutoff
  )
)
```

## `r substring(names(lfc_dfs)[[7]], 7)`

```{r}
# Datatable example
res <- lfc_dfs[[7]]
padj_cutoff <- 0.01
lfc_cutoff <- 0.5

res %>%
  select(SYMBOL, log2FoldChange, padj) %>%
  filter(padj <= padj_cutoff & abs(log2FoldChange) >= lfc_cutoff) %>%
  arrange(padj) %>% 
  DT::datatable() %>%
  DT::formatSignif(columns = 2:3, digits = 3)
```


```{r fig.height=7}
# Volcano plot example
EnhancedVolcano::EnhancedVolcano(
  res,
  lab = res$SYMBOL,
  x = "log2FoldChange",
  y = "padj",
  pCutoff = padj_cutoff,
  FCcutoff = lfc_cutoff,
  subtitle = sprintf(
    "Adjusted p-value cutoff = %0.2f
|Log2FoldChange| cutoff = %0.1f",
    padj_cutoff, lfc_cutoff
  )
)
```



